Allowed Google Analytics tracking
styxlab/next-cms-ghost pull request #161
Opened 2022-01-19 22:48 UTC by dassiorleando

@styxlab I have just added the possibility to set up **Google Analytics** for the website.

First, we need to create a property on Google Analytics side then we copy the **tracking ID (now called measurement ID in version 4)** to be defined in the environment variable called **JAMIFY_GA_MEASUREMENT_ID**.

By default, it read the **gaMeasurementId** variable in **appConfig.ts** file.

I have tested it for a few days now and it's alright.

Do let me know what you think about it, Thanks.

2022-01-27 09:16 UTC, dassiorleando commented
@styxlab 
Is there anything else to be added to this thread? Any chances you looked into?

2022-01-27 17:15 UTC, styxlab commented
Thanks for the PR! Sorry for the delay, but I won't have time before next week to look into it.

2022-02-10 11:26 UTC, styxlab requested changes
Sorry for the long delay. I think the recommended way to include google analytics script in Next.js 12 is to place it into `_app.js` and use the new `next/script` component. Have a look at https://github.com/vercel/next.js/tree/canary/examples/with-google-analytics. Do you think you could update your solution to comply with these best practices?

2022-02-11 11:50 UTC, dassiorleando commented
> Sorry for the long delay. I think the recommended way to include google analytics script in Next.js 12 is to place it into `_app.js` and use the new `next/script` component. Have a look at https://github.com/vercel/next.js/tree/canary/examples/with-google-analytics. Do you think you could update your solution to comply with these best practices?

@styxlab 
I just pushed the required changes, I made sure the `gtab` file is TypeScript friendly.
Thanks for the recommendation.

2022-02-11 15:02 UTC, styxlab approved these changes
Perfect!

2022-02-11 15:02 UTC, merged